os: Visual Studio 2015

platform: x64

# Update *_clear_cache.txt to force re-install
cache:
    - C:\Strawberry -> .appveyor_clear_cache.txt
    - C:\Rakudo -> .appveyor_clear_cache.txt

install:
  - '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64'

  - IF NOT EXIST "C:\Strawberry" choco install strawberryperl
  - SET PATH=C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;%PATH%
  - ps: refreshenv
  - perl -v

  # Install Rakudo Star with chocolately
  # https://chocolatey.org/packages/rakudostar
  - IF NOT EXIST "C:\Rakudo" choco install rakudostar
  - SET PATH=C:\Rakudo\bin;C:\Rakudo\share\perl6\site\bin;%PATH%
  - ps: refreshenv
  - perl6 -v

  # Install via rakudobrew
  #- git clone https://github.com/tadzik/rakudobrew %USERPROFILE%\rakudobrew
  #- SET PATH=%USERPROFILE%\rakudobrew\bin;%PATH%
  #- rakudobrew build moar nom
  #- rakudobrew build zef

  - cd %APPVEYOR_BUILD_FOLDER%
  - zef --verbose --depsonly install .

build: off

test_script:
  - zef --verbose test .
  - zef --verbose install .

branches:
  only:
    - master

shallow_clone: true
